### ISSUE TITLE
Unexpected cyclic substitution loop error

### ISSUE THREAD

**Issue by nareshj09** [akkadotnet/HOCON#128]
Parsing following valid config
```
c: {
    q: {
        a: [2, 5]
    }
}
c: {
    m: ${c.q} {p: 75}
    m.a: ${c.q.a} [6]
}
```

results in exception
```
Unhandled exception. Hocon.HoconParserException: Invalid substitution declaration. A cyclic substitution loop is detected in the Hocon file.. At path 'c.q.a', line 8, position 14.
 ---> Hocon.HoconException: A cyclic substitution loop is detected in the Hocon file.
   at Hocon.Parser.ResolveSubstitution(HoconSubstitution sub)
   at Hocon.Parser.ResolveSubstitutions()
   --- End of inner exception stack trace ---
   at Hocon.Parser.ResolveSubstitutions()
   at Hocon.Parser.ParseText(String text, Boolean resolveSubstitutions, HoconIncludeCallbackAsync includeCallback)
   at Hocon.Parser.Parse(String text, HoconIncludeCallbackAsync includeCallback)
```

EXPECTED:
```
c: {
    q: {
        a: [2, 5]
    }
}
c: {
    m: { a: [2, 5, 6], p: 75 }
}
```

**Comment by IgorFedchenko** [comment]
@Aaronontheweb I have added test to verify this works. 
On the `dev` branch before I have fixed few issues in the milestone, this test was failing (I have just checked that). But after applying latest fixes, this does not reproduce anymore.

I think that this is related to #127 where I have added deep cloning of substituted values - so now when performing substitution it will always be different values in different places, and no cycles are possible.
