### ISSUE TITLE
HOCON bug: System.InvalidOperationException : Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/HOCON#234]
Taken from this PR https://github.com/akkadotnet/akka.net/pull/4212

Failed test: `Akka.Persistence.Sqlite.Tests.Query.SqliteCurrentEventsByPersistenceIdSpec.ReadJournal_CurrentEventsByPersistenceId_should_return_empty_stream_for_empty_journal_from_0_to_0`

Looks like the stuff we do to rebuild the `ActorSystem.Settings.Config` with the `InjectTopLevelFallback` calls blows up HOCON or something calling it.

```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.

at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Hocon.HoconObject.Clone(IHoconElement newParent)
   at Hocon.HoconValue.Clone(IHoconElement newParent)
   at Hocon.HoconField.Clone(IHoconElement newParent)
   at Hocon.HoconObject.Clone(IHoconElement newParent)
   at Hocon.HoconValue.Clone(IHoconElement newParent)
   at Hocon.HoconField.Clone(IHoconElement newParent)
   at Hocon.HoconObject.Clone(IHoconElement newParent)
   at Hocon.HoconValue.Clone(IHoconElement newParent)
   at Hocon.Config..ctor(HoconRoot source)
   at Akka.Dispatch.MessageDispatcherConfigurator..ctor(Config config, IDispatcherPrerequisites prerequisites) in D:\a\2\s\src\core\Akka\Dispatch\AbstractDispatcher.cs:line 262
   at Akka.TestKit.CallingThreadDispatcherConfigurator..ctor(Config config, IDispatcherPrerequisites prerequisites) in D:\a\2\s\src\core\Akka.TestKit\CallingThreadDispatcher.cs:line 26
   at Akka.TestKit.TestKitBase.InitializeTest(ActorSystem system, Config config, String actorSystemName, String testActorName) in D:\a\2\s\src\core\Akka.TestKit\TestKitBase.cs:line 132
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, ActorSystem system, Config config, String actorSystemName, String testActorName) in D:\a\2\s\src\core\Akka.TestKit\TestKitBase.cs:line 102
   at Akka.TestKit.TestKitBase..ctor(ITestKitAssertions assertions, ActorSystem system, String testActorName) in D:\a\2\s\src\core\Akka.TestKit\TestKitBase.cs:line 77
   at Akka.TestKit.TestProbe..ctor(ActorSystem system, ITestKitAssertions assertions, String testProbeName) in D:\a\2\s\src\core\Akka.TestKit\TestProbe.cs:line 32
   at Akka.TestKit.TestKitBase.CreateTestProbe(ActorSystem system, String name) in D:\a\2\s\src\core\Akka.TestKit\TestKitBase.cs:line 545
   at Akka.TestKit.TestKitBase.CreateTestProbe(String name) in D:\a\2\s\src\core\Akka.TestKit\TestKitBase.cs:line 534
   at Akka.Streams.TestKit.TestSubscriber.ManualProbe`1..ctor(TestKitBase testKit) in D:\a\2\s\src\core\Akka.Streams.TestKit\TestSubscriber.cs:line 82
   at Akka.Streams.TestKit.TestSubscriber.Probe`1..ctor(TestKitBase testKit) in D:\a\2\s\src\core\Akka.Streams.TestKit\TestSubscriber.cs:line 489
   at Akka.Streams.TestKit.TestSubscriber.CreateSubscriberProbe[T](TestKitBase testKit) in D:\a\2\s\src\core\Akka.Streams.TestKit\TestSubscriber.cs:line 546
   at Akka.Streams.TestKit.StreamTestKit.ProbeSink`1.Create(MaterializationContext context, Probe`1& materializer) in D:\a\2\s\src\core\Akka.Streams.TestKit\StreamTestKit.cs:line 167
   at Akka.Streams.Implementation.SinkModule`2.Akka.Streams.Implementation.ISinkModule.Create(MaterializationContext context, Object& materializer) in D:\a\2\s\src\core\Akka.Streams\Implementation\Sinks.cs:line 101
   at Akka.Streams.Implementation.ActorMaterializerImpl.ActorMaterializerSession.MaterializeAtomic(AtomicModule atomic, Attributes effectiveAttributes, IDictionary`2 materializedValues) in D:\a\2\s\src\core\Akka.Streams\Implementation\ActorMaterializerImpl.cs:line 133
   at Akka.Streams.Implementation.MaterializerSession.MaterializeModule(IModule module, Attributes effectiveAttributes) in D:\a\2\s\src\core\Akka.Streams\Implementation\StreamLayout.cs:line 2365
   at Akka.Streams.Implementation.MaterializerSession.MaterializeModule(IModule module, Attributes effectiveAttributes) in D:\a\2\s\src\core\Akka.Streams\Implementation\StreamLayout.cs:line 2370
   at Akka.Streams.Implementation.MaterializerSession.Materialize() in D:\a\2\s\src\core\Akka.Streams\Implementation\StreamLayout.cs:line 2278
   at Akka.Streams.Implementation.ActorMaterializerImpl.Materialize[TMat](IGraph`2 runnable, Func`2 subFlowFuser, Attributes initialAttributes) in D:\a\2\s\src\core\Akka.Streams\Implementation\ActorMaterializerImpl.cs:line 395
   at Akka.Streams.Implementation.ActorMaterializerImpl.Materialize[TMat](IGraph`2 runnable) in D:\a\2\s\src\core\Akka.Streams\Implementation\ActorMaterializerImpl.cs:line 349
   at Akka.Streams.Dsl.Runna
```

**Comment by Aaronontheweb** [comment]
closed via https://github.com/akkadotnet/HOCON/pull/237
