### ISSUE TITLE
HOCON Immutability error

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/HOCON#261]
```
webcrawler.trackerservice_1  |  ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
webcrawler.trackerservice_1  |  ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
webcrawler.trackerservice_1  |    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
webcrawler.trackerservice_1  |    at Hocon.HoconField.SetValue(HoconValue value)
webcrawler.trackerservice_1  |    at Hocon.HoconObject.Merge(HoconObject other)
webcrawler.trackerservice_1  |    at Hocon.HoconObject.Merge(HoconObject other)
webcrawler.trackerservice_1  |    at Hocon.HoconMergedObject..ctor(IHoconElement parent, List`1 objects)
webcrawler.trackerservice_1  |    at Hocon.HoconValue.GetObject()
webcrawler.trackerservice_1  |    at Hocon.HoconObject.TryGetField(HoconPath path, HoconField& result)
webcrawler.trackerservice_1  |    at Hocon.HoconObject.TryGetValue(HoconPath path, HoconValue& result)
webcrawler.trackerservice_1  |    at Hocon.Config.GetConfig(HoconPath path)
webcrawler.trackerservice_1  |    at Hocon.Config.GetConfig(String path)
webcrawler.trackerservice_1  |    at Akka.Serialization.SerializerIdentifierHelper.GetSerializerIdentifierFromConfig(Type type, ExtendedActorSystem system)
webcrawler.trackerservice_1  |    at Akka.Serialization.Serializer.<>c__DisplayClass2_0.<.ctor>b__0()
webcrawler.trackerservice_1  |    at Akka.Util.FastLazy`1.get_Value()
webcrawler.trackerservice_1  |    at Akka.Serialization.Serialization..ctor(ExtendedActorSystem system)
webcrawler.trackerservice_1  |    at Akka.Actor.Internal.ActorSystemImpl.ConfigureSerialization()
webcrawler.trackerservice_1  |    at Akka.Actor.Internal.ActorSystemImpl.Akka.Actor.Internal.ISupportSerializationConfigReload.ReloadSerialization()
webcrawler.trackerservice_1  |    at Akka.Actor.Settings.RebuildConfig()
webcrawler.trackerservice_1  |    at Akka.Actor.Settings.InjectTopLevelFallback(Config config)
webcrawler.trackerservice_1  |    at Akka.Streams.ActorMaterializer.Create(IActorRefFactory context, ActorMaterializerSettings settings, String namePrefix)
webcrawler.trackerservice_1  |    at Akka.Streams.ActorMaterializerExtensions.Materializer(IActorRefFactory context, ActorMaterializerSettings settings, String namePrefix
```

Run https://github.com/petabridge/Cluster.WebCrawler on the `dev` branch using `docker-compose up` after calling `build.cmd Docker` - submit a crawl through the UI and there's a chance this might show up.

**Comment by Aaronontheweb** [comment]
Found another issue - same project:

```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Hocon.HoconField.Clone(IHoconElement newParent)
   at Hocon.HoconObject.Clone(IHoconElement newParent)
   at Hocon.HoconValue.Clone(IHoconElement newParent)
   at Hocon.HoconField.Clone(IHoconElement newParent)
   at Hocon.HoconObject.Clone(IHoconElement newParent)
   at Hocon.HoconValue.Clone(IHoconElement newParent)
   at Hocon.HoconField.Clone(IHoconElement newParent)
   at Hocon.HoconObject.Clone(IHoconElement newParent)
   at Hocon.HoconValue.Clone(IHoconElement newParent)
   at Hocon.HoconField.Clone(IHoconElement newParent)
   at Hocon.HoconObject.Clone(IHoconElement newParent)
   at Hocon.HoconValue.Clone(IHoconElement newParent)
   at Hocon.Config.InsertFallbackValue(HoconValue value)
   at Hocon.Config..ctor(HoconRoot root)
   at Hocon.Config..ctor(HoconRoot root, Config fallback)
   at Hocon.Config.WithFallback(Config fallback)
   at Akka.HealthCheck.Configuration.HealthCheckSettings..ctor(ActorSystem system)
   at Akka.HealthCheck.AkkaHealthCheckExt.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.CreateExtension(ExtendedActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.<>c__DisplayClass56_0.<RegisterExtension>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Akka.Actor.Internal.ActorSystemImpl.TryGetExtension(Type extensionType, Object& extension)
   at Akka.Actor.Internal.ActorSystemImpl.GetExtension(IExtensionId extensionId)
   at Akka.Actor.ExtensionIdProvider`1.Get(ActorSystem system)
   at Akka.Actor.ExtensionIdProvider`1.Akka.Actor.IExtensionId.Get(ActorSystem system)
   at Akka.Actor.Internal.ActorSystemImpl.RegisterExtension(IExtensionId extension)
   at Akka.Actor.Internal.ActorSystemImpl.ConfigureExtensions(IEnumerable`1 extensionIdProviders)
   at Akka.Actor.Internal.ActorSystemImpl.Start()
   at Akka.Actor.ActorSystem.CreateAndStartSystem(String name, Config withFallback)
   at Akka.Actor.ActorSystem.Create(String name, Config config)
   at WebCrawler.TrackerService.TrackerService.Start() in C:\Repositories\petabridge\Cluster.WebCrawler\src\WebCrawler.TrackerService\TrackerService.cs:line 28
   at WebCrawler.TrackerService.Program.Main(String[] args) in C:\Repositories\petabridge\Cluster.WebCrawler\src\WebCrawler.TrackerService\Program.cs:line 18
```

**Comment by Aaronontheweb** [comment]
In both of these cases issue was caused by a plugin (Akka.Streams in one, Akka.Healthcheck in another) reloading the top-level configuration at startup.

**Comment by Aaronontheweb** [comment]
Not going to fix this. See HOCON 3.0 spec coming soon.
